### PR TITLE
http get: example; pin to v1.17.0 stable toolchain

### PR DESCRIPTION
**Pull request by Horki**
@jimblandy due to "reqwest" is on `v0.5.1` I have pinned to older toolchain; because with (v.1.48.0 stable) It's not building

### CODE REVIEW

**Comment by jimblandy** [comment]
Thanks for the pull request and bug report. Pinning back to a 2017 version of Rust seems a bit drastic. I updated to reqwest 0.9, and it seems to build fine. Does that work for you?

**Comment by jimblandy** [comment]
9b8d21b fixes this for me. If you can confirm, we'll close this.

**Comment by Horki** [comment]
@jimblandy yes works now, thanks!

**Comment by jimblandy** [comment]
Fantastic - thanks again.

**Pull request closed without merging**
